apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  labels:
    app: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app-storage
          mountPath: /usr/share/nginx/html
        # Добавляем тестовую страницу
        command: ['/bin/sh', '-c']
        args:
          - |
            echo "<html><body><h1>App2 - Persistent Data</h1><p>Host: $(hostname)</p><p>Time: $(date)</p></body></html>" > /usr/share/nginx/html/index.html
            exec nginx -g 'daemon off;'
      volumes:
      - name: app-storage
        persistentVolumeClaim:
          claimName: app2-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app2-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-custom
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: app2-service
spec:
  selector:
    app: app2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP