apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-pool1
  namespace: metallb-system
spec:
  addresses:
  - 10.8.11.232-10.8.11.240 # Выделить диапазон

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - metallb-pool1