apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minio
type: Opaque
data:
  rootUser: bWluaW9hZG1pbg==  # minioadmin (base64)
  rootPassword: YWRtaW4xMjM0NTY=  # admin123456 (base64) - ЗАМЕНИТЕ!